apiVersion: v1
kind: Service
metadata:
  labels: {{ include "labels" . | nindent 4 }} {{ cat "app: autoscaler," .Chart.Name | nindent 4 }} {{ "serving.knative.dev/release: devel" | nindent 4 }}
  name: autoscaler
  namespace: knative-serving
spec:
  ports:
  - name: http
    port: {{ .Values.autoscaler.http.port }}
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: {{ .Values.autoscaler.metrics.port }}
    protocol: TCP
    targetPort: 9090
  selector:
    app: autoscaler
  template:
    metadata:
      labels: {{ include "noVersionlabels" . | nindent 8 }} {{ cat "app:" .Chart.Name | nindent 8 }}
